name: SonarQube Analysis

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Add this line to enable manual trigger

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install SonarScanner
        run: npm install -g sonarqube-scanner

      - name: Run SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=anubhav.nodejs \
            -Dsonar.organization=anubhavkumar321 \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
